import RewardIcon1 from './Icons/icon1.png'
export const DATA = [
    {
        YeallowBTN: 'Повысить цитируемость воих...',
        GreenBTN:'Engineering/Material',
        CartTitle: 'Вопросы проектирования трансатлантического межнационального продуктопровода в условиях ',
        CommentText: 'Могу ещё помочь со статистической обработкой больших массивов',
        RewardImg: RewardIcon1,
        RewardText: '---',
        key__btn1: 'первый ключ',
        key__btn2: 'второй ключ',
        key__btn3: '+5',
    },
    {
        YeallowBTN:'Повысить цитируемость своих ...',
        CartTitle:'Вопросы проектирования трансатлантического межнационального продуктопровода в условиях нарастающей коронавирусной пандемии ',
        GreenBTN:'Engineering/Material',
        CommentText:'Могу ещё помочь со статистической обработкой больших массивов',
        RewardImg:RewardIcon1,
        RewardText:'Услуга',
        key__btn1:'первый ключ',
        key__btn2:'второй ключ',
        key__btn3:'третий ключ',
    },
    {
        YeallowBTN:'Повысить цитируемость своих ...',
        CartTitle:'Вопросы проектирования трансатлантического межнационального продуктопровода в условиях нарастающей коронавирусной пандемии на примере использования методов дистанцион...',
        GreenBTN:'Engineering/Material',
        CommentText:'Могу ещё помочь со статистической обработкой больших массивов',
        RewardImg:RewardIcon1,
        RewardText:'$100',
        key__btn1:'первый ключ',
        key__btn2:'второй ключ',
        key__btn3:'третий ключ',
    },
    {
        YeallowBTN:'Повысить цитируемость своих ...',
        CartTitle:'Вопросы проектирования  ',
        GreenBTN:'Engineering/Material',
        CommentText:'Могу ещё помочь со статистической обработкой больших массивов',
        RewardImg:RewardIcon1,
        RewardText:'Ответная помощь',
        key__btn1:'первый ключ',
        key__btn2:'второй ключ',
        key__btn3:'третий ключ',
    },
]